/*
 * Storage Scales
 *
 * 💪💪 It is an application that calculates the size of files under a directory and returns them in JSON format.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package scales

// Size Store the size of the files under the directory by unit
type Size struct {
	Kb int64   `json:"kb,omitempty"`
	Mb float32 `json:"mb,omitempty"`
	Gb float32 `json:"gb,omitempty"`
}
