version: '3'

services: 
  storage:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: storage-scale:latest
    container_name: storage-scale
    ports:
      - 8080:8080
    environment: 
      ACCESS_CONTROL_ALLOW_ORIGIN: "http://localhost"
      BASE_DIR: "/share/misc"
      EXCLUDE: ignore,ignore2
      IS_DEBUG_MODE: "false"
    volumes: 
      - /tmp:/share/misc
